# Generated by Django 3.2.15 on 2022-10-05 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 15, 14, 25, 683924)),
        ),
    ]
