# Generated by Django 3.2.15 on 2022-10-05 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221005_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 15, 21, 0, 137103)),
        ),
    ]
