# Generated by Django 3.2.15 on 2022-10-06 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221005_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 17, 3, 16, 595814), null=True),
        ),
    ]
