# Generated by Django 3.2.15 on 2022-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221006_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='who_uploaded',
            field=models.CharField(default='asd', max_length=105),
        ),
    ]
