# Generated by Django 3.2.15 on 2022-10-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221010_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='who_uploaded',
            field=models.CharField(max_length=105, null=True),
        ),
    ]
