# Generated by Django 3.2.15 on 2022-10-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_article_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
