# Generated by Django 3.2.15 on 2022-10-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20221014_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes_count',
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_liked', models.JSONField()),
                ('users_disliked', models.JSONField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.article')),
            ],
        ),
    ]
