# Generated by Django 3.2.15 on 2022-10-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_article_id_mark_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
    ]
